name: test
version: 3.3
networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 10.13.2.0/24
      driver: default
  frontend:
    driver: bridge
    ipam:
      config:
      - subnet: 10.13.1.0/24
      driver: default
product:
  location: PRC
  port: 3000
  redis:
    host: localhost
services:
  dnsmasq:
    cap_add:
    - NET_ADMIN
    container_name: dnsmasq
    image: andyshinn/dnsmasq
    networks:
    - backend
    ports:
    - 53:53/tcp
    - 53:53/udp
    restart: always
    volumes:
    - /home/conf/dnsmasq/dnsmasq.conf: /etc/dnsmasq.conf
    - /home/conf/dnsmasq: /etc/dnsmasq.d
    - /etc/hosts: /etc/hosts
  go:
    container_name: go
    environment:
    - GO111MODULE=on
    - GOPROXY=https://goproxy.cn,direct
    image: golang:1.13
    networks:
    - frontend
    - backend
    ports:
    - "3000": 3000
    tty: true
    volumes:
    - /home/kee/www/tiris: /go
    - /home/kee: /home/kee
  mariadb:
    command:
    - mysqld
    - ','
    - --character-set-server=utf8
    container_name: mariadb
    environment:
      TZ: Asia/Shanghai
    image: mariadb:latest
    networks:
    - backend
    ports:
    - 3306:3306
    restart: always
    volumes:
    - /home/conf/mysql: /etc/mysql
    - /home/data/mysql: /var/lib/mysql
  mongo:
    command:
    - /usr/bin/mongod
    - ','
    - -f
    - ','
    - /etc/mongodb/mongo.conf
    container_name: mongo
    image: mongo
    networks:
    - backend
    ports:
    - 27017:27017
    restart: always
    volumes:
    - /home/conf/mongodb: /etc/mongodb
    - /home/data/mongodb: /data/mongodb
  nginx:
    container_name: nginx
    depends_on:
    - php
    image: nginx
    networks:
      frontend:
        ipv4_address: 10.13.1.10
    ports:
    - 80:80
    - 8080:8080
    - 443:443
    restart: always
    volumes:
    - /home/conf/nginx: /etc/nginx
    - /home/kee/www: /var/www
  php:
    container_name: php
    depends_on:
    - redis
    - mongo
    environment:
    - beian-api=/var/www/xmisp/dj/beian-api
    image: kee/php:7.1-fpm
    networks:
    - frontend
    - backend
    restart: always
    volumes:
    - /home/kee/www: /var/www
    - /home/kee/.bin/phpunit: /usr/local/bin/phpunit
    - /home/kee/.ssh: /root/.ssh
    - /home/conf/php71: /usr/local/etc
  redis:
    container_name: redis
    image: redis:latest
    networks:
    - backend
    ports:
    - "6379": 6379
    restart: always
  ss:
    container_name: ss
    environment:
      SS_PASSWORD: keesely.net
      SS_SERVER_PORT: 12700
    image: guolin/shadowsocks
    networks:
    - frontend
    ports:
    - "12700": 12700
    restart: always
stage:
  debug: true
  env: stage
  location: PRC
  port: 3000
  redis:
    host: localhost
